### PR TITLE
Offset the hat by 40 x instead of 40 y

### LINKED ISSUE #102: [Bug]: FTB Chunks not rendering the player's hat
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge-1605.3.2-build.79.jar

### Forge / Fabric version

forge-1.16.5-36.2.4.jar

### Modpack & version

Enigmatica 6 0.5.19

### What issue are you having?

as reported here, the hat part doesn't render in either the map or in the wip teams gui: https://github.com/NillerMedDild/Enigmatica6/issues/3627

my skin at the time:
343ff627de2718b599134660b2cf376e84bc62d241fd15cfafec3789a688e77e

some relevant lines:
https://github.com/search?q=org%3AFTBTeam+getFace&type=code
https://github.com/FTBTeam/FTB-Library/blob/ed5e041819999eedee56a40ebbf75f9339d90236/common/src/main/java/dev/ftb/mods/ftblibrary/icon/FaceIcon.java#L41

### Crashlogs

_No response_

### Steps to reproduce

Gaze upon the minimap whilst your skin has a hat like mine

### Anything else to note?

Steve skin, not Alex

### PR DESCRIPTION
**Pull request by Quezler**
> fixes https://github.com/FTBTeam/FTB-Mods-Issues/issues/102 for https://github.com/NillerMedDild/Enigmatica6/issues/3627 :3

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
@LatvianModder @MaxNeedsSnacks please review

**Comment by MaxNeedsSnacks** [comment]
Beat me to it Mikey haha

**Review by MaxNeedsSnacks — APPROVED** [review]
LGTM, how did you not notice this Lat :smile:

**Comment by MaxNeedsSnacks** [comment]
Also @Quezler please rebase this onto dev if you can, to keep the commit history clean ^^

**Comment by Quezler** [comment]
ill try, didn't see a contributing.md anywhere saying which branch to use, and some of the other pulls targeted main too ^

**Review by MaxNeedsSnacks — APPROVED** [review]

**Pull request merged**
